name: ostad_flutter_batch_two
description: Flutter project for ostad batch two live class


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: any
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.2.1
  http: ^0.13.5
  shared_preferences: any
  firebase_core: ^2.9.0
  firebase_auth: ^4.6.3
  cloud_firestore: any
  image_picker: ^0.8.9
  firebase_storage: ^11.1.0
  path_provider: ^2.0.14
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
